# Generated by Django 5.1.15 on 2026-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorereport",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline (prototype heuristic)"),
                    ("canonical", "Canonical (weighted spec)"),
                ],
                default="baseline",
                max_length=16,
            ),
        ),
    ]
