# Generated by Django 5.1.15 on 2026-05-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_scorereport_algorithm"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bank_statements/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("parsed_features", models.JSONField(default=dict)),
                ("txn_count", models.PositiveIntegerField(default=0)),
                ("period_months", models.FloatField(default=0)),
                ("parse_notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
