# Generated by Django 5.1.15 on 2026-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bankstatement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorereport",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline (prototype heuristic)"),
                    ("canonical", "Weighted Score Algorithm"),
                ],
                default="baseline",
                max_length=16,
            ),
        ),
    ]
