# Generated by Django 5.1.15 on 2026-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_scorereport_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Manual upload"),
                    ("aa_fetch", "Account Aggregator fetch"),
                ],
                default="upload",
                max_length=16,
            ),
        ),
    ]
