# Generated by Django 5.1.15 on 2026-07-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bankstatement_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorereport',
            name='ai_assessment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='algorithm',
            field=models.CharField(choices=[('baseline', 'Baseline (prototype heuristic)'), ('canonical', 'Weighted Score Algorithm'), ('ai_model', 'AI Model (alternative-data, 1-100)')], default='baseline', max_length=16),
        ),
    ]
