# Generated by Django 5.1.15 on 2026-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scorereport_ai_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('Doctorate', 'Doctorate'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate')], max_length=40),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scorereport',
            name='algorithm',
            field=models.CharField(choices=[('baseline', 'Baseline (prototype heuristic)'), ('canonical', 'Weighted Score Algorithm'), ('ai_model', 'AI Model (alternative-data, 1-100)')], default='ai_model', max_length=16),
        ),
    ]
