# Generated by Django 5.1.15 on 2026-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customerprofile_education_customerprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereport',
            name='algorithm',
            field=models.CharField(choices=[('ai_model', 'AI Model (alternative-data, 1-100)')], default='ai_model', max_length=16),
        ),
    ]
