# Generated by Django 5.1.15 on 2026-08-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_scorereport_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
